export default {
  homePage: "/",
  singleBook: "/singleBook/:id",
  singleNews: "/singleNews/:id",
  news: "/news",
  books: "/books",
  directories: "/directories",
  cinemaSchedules: "/cinemaSchedules",
  addNews: "/addNews",
  addBooks: "/addBooks",
  addDirectories: "/addDirectories",
  addMovies: "/addMovies",
  adminPannel: "/adminPannel",
  AboutUs: "/AboutUs",
  termsAndConditions: "/termsAndConditions",
  aboutUs: "/aboutUs",
  privacyPolicy: "/privacyPolicy",
  contactUs: "/contactUs",

};
